### ISSUE TITLE
유저는 모먼트를 추가할 수 있다. (모먼트 추가 페이지)

### ISSUE THREAD

**Issue by Choe-Ji-Hwan** [boostcampwm-2022/android06-mogle#4]
## 🚀 기능 설명
- 유저는 모먼트를 추가할 수 있다. (모먼트 추가 페이지)

## 📝 Task (To-do):
- [x] 사진 여러장(최대 5장)을 버튼으로 추가하고, 삭제할 때는 추가한 것을 x 버튼으로 삭제한다.
- [x] 날짜는 오늘 날짜로 설정되어 있지만, Text를 누르면 캘런더가 나와서 설정할 수 있다.
- [x] 내용 칸에는 해당 모먼트 내용을 입력한다. (최대 500자)
- [x] 장소는 일단 더미값을 가진다.
- [x] 글로브를 메뉴 형태로 보고 선택할 수 있다.(더미)
- [x] 추가 버튼이 존재한다.

## 📢 추가 사항
- 앨범이 아직 만들어지지 않아서, _더미 값_을 넣어둔다.
- 장소 페이지가 아직 만들어지지 않아서, _더미 값_을 넣어둔다.
