### ISSUE TITLE
유저는 글로브를 볼 수 있고 / 추가할 수 있다.

### ISSUE THREAD

**Issue by Choe-Ji-Hwan** [boostcampwm-2022/android06-mogle#50]
## 🚀 기능 설명
앨범을 볼 수 있는 기능
+ 앨범을 추가할 수 있는 기능

## 📝 Task (To-do):
 - [x] 바텀 네비게이션에서 글로브 선택시 나타나는 글로브 UI 구현
 - [x] 상단 뷰를 위로 올리면 AppBar(ToolBar)안에 글자와 +버튼이 모두 들어가는 것 구현
 - [x] 글로브 추가버튼 클릭시 추가 하는 다이얼로그 구현
 - [x] 글로브 추가 로직 구현

## 📢 추가 사항
- 이후에 상세 글로브 구현 / 모먼트 추가 페이지 / 모먼트 삭제 페이지 순으로 UI 작업을 완료할 것 같습니다.
