### ISSUE TITLE
유저는 검색 부분에서 날씨 정보를 볼 수 있다.

### ISSUE THREAD

**Issue by jaemin-Yoo** [boostcampwm-2022/android06-mogle#6]
## 🚀 기능 설명
검색창 옆에 있는 날씨 위젯 UI

## 📝 Task (To-do):
 - [x] 레이아웃 작성
 - [x] 날씨 데이터에 맞게 아이콘 변경
 - [x] 날씨 데이터에 맞게 온도 변경
 - [x] UiState를 통한, 상태별 화면 출력

## 📢 추가 사항
추가 및 특이사항 또는 구현할 디자인을 작성해 주세요.
