### ISSUE TITLE
유저는 상세 글로브 모먼트를 볼 수 있고 해당 글로브를 수정하거나 삭제할 수 있다.

### ISSUE THREAD

**Issue by Choe-Ji-Hwan** [boostcampwm-2022/android06-mogle#67]
## 🚀 기능 설명
상세 글로브에 대한 내용입니다. 
1. 상세 글로브 내 모먼트 보이기, 상세 글로브 내부의 모먼트의 클릭리스너 -> 모먼트 상세페이지
2. 상세 글로브에서 해당 글로브 이름 수정
3. 상세 글로브에서 해당 글로브 삭제

## 📝 Task (To-do):
- [x] 상세 글로브 페이지 완성
- [x] 해당 글로브의 이름 수정
- [x] 해당 글로브 삭제 ( + 경고 다이얼로그 )

## 📢 추가 사항
이후에 추가할 것은, 모먼트 추가 페이지 / 모먼트 삭제 페이지 입니다.
